on:
    push:
        branches:
            - main
name: Run everything
jobs:
    run:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - uses: quarto-dev/quarto-actions/setup@v2
            - uses: r-lib/actions/setup-r@v2
              with:
                r-version: 'renv'
            - uses: r-lib/actions/setup-renv@v2
            - name: Run with whirl
              shell: bash
              run: Rscript runner.R